### ISSUE TITLE
Uncaught Error: Class 'Composer\Repository\RepositorySet' not found after installation and run

### ISSUE THREAD

**Issue by finwe** [dg/composer-frontline#1]
No matter how I install the plugin (globally or locally), I get following error when running `composer frontline`

PHP version is 7.4.11, composer version is 1.10.16.

```
$ devel > composer frontline
PHP Fatal error:  Uncaught Error: Class 'Composer\Repository\RepositorySet' not found in /.../vendor/dg/composer-frontline/src/UpdateCommand.php:137
Stack trace:
#0 /.../vendor/dg/composer-frontline/src/UpdateCommand.php(75): DG\ComposerFrontline\UpdateCommand->createVersionSelector()
#1 /.../vendor/dg/composer-frontline/src/UpdateCommand.php(54): DG\ComposerFrontline\UpdateCommand->updatePackages()
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): DG\ComposerFrontline\UpdateCommand->execute()
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#4 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#5 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(281): Symfony\Component\Console\Application->doRun()
#6 phar:///usr/local/bin/c in /.../vendor/dg/composer-frontline/src/UpdateCommand.php on line 137

Fatal error: Uncaught Error: Class 'Composer\Repository\RepositorySet' not found in /.../vendor/dg/composer-frontline/src/UpdateCommand.php:137
Stack trace:
#0 /.../vendor/dg/composer-frontline/src/UpdateCommand.php(75): DG\ComposerFrontline\UpdateCommand->createVersionSelector()
#1 /.../vendor/dg/composer-frontline/src/UpdateCommand.php(54): DG\ComposerFrontline\UpdateCommand->updatePackages()
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): DG\ComposerFrontline\UpdateCommand->execute()
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#4 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#5 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(281): Symfony\Component\Console\Application->doRun()
#6 phar:///usr/local/bin/c in /.../vendor/dg/composer-frontline/src/UpdateCommand.php on line 137
```

**Comment by dg** [comment]
Ha! RepositorySet is part of composer-plugin-api 2.0.0. I'll try to get around it.
